# 12. Principal component analysis 1

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## 12.6 Implementations 

In [2]:
X = np.array([[-7, -2], [-3, -3], [4, 1], [6, 4]])

In [3]:
from sklearn.decomposition import PCA 
pca = PCA(n_components=2)
pca.fit(X)

PCA(n_components=2)

In [4]:
pca.components_ # Principal components

array([[-0.89920519, -0.43752718],
       [ 0.43752718, -0.89920519]])

In [5]:
pca.singular_values_ ** 2 # Eigen values

array([134.81512169,   5.18487831])

In [6]:
pca.transform(X)

array([[ 7.16949066, -1.26427988],
       [ 4.0101971 ,  1.38503402],
       [-4.03434793,  0.85090353],
       [-7.14533984, -0.97165767]])

## 12.7 Exercise    

In [8]:
X = np.array([[-7, -2], [-3, -3], [4, 1], [6, 4]])
S = np.dot(X.T, X)
print(S)

[[110  51]
 [ 51  30]]


In [11]:
values, vectors = np.linalg.eig(S)
print(values)
print(vectors)

[134.81512169   5.18487831]
[[ 0.89920519 -0.43752718]
 [ 0.43752718  0.89920519]]


In [30]:
print(f'the first principal component: {vectors[:, 0]}')
print(f'variance along the first principal component axis: {values[0]}')
print(f'the second principal component: {vectors[:, 1]}')
print(f'variance along the second principal component axis: {values[1]}')


the first principal component: [0.89920519 0.43752718]
variance along the first principal component axis: 134.81512169239522
the second principal component: [-0.43752718  0.89920519]
variance along the second principal component axis: 5.184878307604791


In [31]:
first = np.dot(X, vectors[:, 0])
second = np.dot(X, vectors[:, 1])
print(f'principal component score:\n {np.stack((first, second)).T}')

principal component score:
 [[-7.16949066  1.26427988]
 [-4.0101971  -1.38503402]
 [ 4.03434793 -0.85090353]
 [ 7.14533984  0.97165767]]
